Select * FROM detail;
Select * FROM discount;
Select * FROM booking;
Select * FROM credit_card;
Select * FROM room;
Select * FROM room_type;
Select * FROM hotel;
Select * FROM staff;
Select * FROM customer;